CREATE TABLE IF NOT EXISTS user (
	id INTEGER IDENTITY PRIMARY KEY ,
	name VARCHAR(255) NOT NULL,
	age INTEGER
);

CREATE TABLE IF NOT EXISTS role (
	id INTEGER IDENTITY PRIMARY KEY ,
	name VARCHAR(255) NOT NULL
);
